# Generated by Django 3.2.13 on 2022-06-23 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(to='recipe.Tag'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(help_text='Название продукта', on_delete=django.db.models.deletion.CASCADE, to='recipe.ingredient', verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_id',
            field=models.ForeignKey(help_text='Ингредиент блюда', on_delete=django.db.models.deletion.CASCADE, to='recipe.recipe', verbose_name='Название рецепта'),
        ),
    ]
