# Generated by Django 2.2 on 2022-06-15 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_auto_20220615_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_id',
            field=models.ForeignKey(help_text='Ингредиент блюда', on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipe.Recipe'),
        ),
    ]
