# Generated by Django 2.2 on 2022-06-20 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0005_auto_20220616_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='ingredient',
            field=models.ForeignKey(help_text='Название продукта', on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipe.Ingredient', verbose_name='Название продукта'),
        ),
        migrations.AlterField(
            model_name='recipeingredient',
            name='recipe_id',
            field=models.ForeignKey(help_text='Ингредиент блюда', on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipe.Recipe'),
        ),
    ]
