# Generated by Django 2.2 on 2022-06-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0007_auto_20220620_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=0, upload_to='recipes_img/', verbose_name='Картинка для рецепта'),
            preserve_default=False,
        ),
    ]
